@extends('layouts.app')
@section('title', 'About')
@section('page-title', 'About OnePercent')
@section('page-subtitle', 'Our story and mission')

@section('content')
    <div class="max-w-2xl fade-in">
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">

            {{-- Hero --}}
            <div class="bg-gradient-to-br from-primary to-primary-dark p-12 text-center text-white">
                <div
                    class="w-20 h-20 bg-white rounded-3xl flex items-center justify-center
                        mx-auto mb-4 text-4xl font-bold">
                    <img src="/img/onboard1.png" alt="">
                </div>
                <h2 class="text-2xl font-bold mb-2">Why This App Was Created?</h2>
                <p class="text-white/80">Making daily improvement accessible to everyone</p>
            </div>

            {{-- Content --}}
            <div class="p-8 space-y-6 text-gray-600 leading-relaxed">
                <p>
                    <strong class="text-gray-800">OnePercent</strong> is a productivity app designed
                    to help you become 1% better every day through daily AI-powered challenges.
                </p>
                <p>
                    Each day, you receive simple challenges that can be completed in a short amount
                    of time. By staying consistent, you can build streaks, earn achievements,
                    and track your progress over time.
                </p>
                <p>
                    We believe that small daily improvements lead to meaningful growth.
                    Whether it's learning a new skill, staying healthy, or managing your finances —
                    OnePercent guides you with personalized, AI-generated challenges tailored
                    to your interests.
                </p>

                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 py-4">
                    @foreach ([['img' => '/img/bot.png', 'title' => 'AI-Powered', 'desc' => 'Challenges generated by Gemini AI'], ['img' => '/img/streak.png', 'title' => 'Streak System', 'desc' => 'Build daily momentum'], ['img' => '/img/1st.png', 'title' => 'Leaderboard', 'desc' => 'Compete with friends'], ['img' => '/img/trophy.png', 'title' => 'Achievements', 'desc' => 'Unlock milestones']] as $f)
                        <div
                            class="bg-slate-50/60 border border-slate-100 rounded-2xl p-5 text-center transition-all duration-300 hover:bg-white hover:border-[#B28CFF]/30 hover:shadow-lg hover:shadow-[#9261F3]/5 group">
                            <div
                                class="w-16 h-16 mx-auto mb-3 p-2 bg-white rounded-xl shadow-sm border border-slate-100 flex items-center justify-center transition-transform duration-300 group-hover:scale-110">
                                <img src="{{ $f['img'] }}" alt="{{ $f['title'] }}"
                                    class="w-full h-full object-contain filter drop-shadow-sm">
                            </div>
                            <h4
                                class="font-black text-slate-800 text-sm tracking-tight group-hover:text-[#9261F3] transition-colors duration-200">
                                {{ $f['title'] }}
                            </h4>
                            <p class="text-xs font-medium text-slate-400 mt-1 leading-normal px-2">
                                {{ $f['desc'] }}
                            </p>

                        </div>
                    @endforeach
                </div>

                <div class="text-center pt-4 border-t border-gray-100">
                    <p class="text-xl font-bold text-primary">1% Better Every Day.</p>
                    <p class="text-sm text-gray-400 mt-1">Version 1.0.0</p>
                </div>
            </div>
        </div>
    </div>
@endsection
