@extends('layouts.app')
@section('title', 'Terms & Conditions')
@section('page-title', 'Terms and Conditions')
@section('page-subtitle', 'Please read carefully')

@section('content')
    <div class="max-w-2xl fade-in">
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 space-y-6">

            <p class="text-gray-500">
                By using the OnePercent app, you agree to the following terms:
            </p>

            @foreach ([
            ['1. Account', ['One account per user.', 'You are responsible for keeping your account secure.', 'Do not share your credentials with others.']],
            ['2. Challenge & Streak', ['Challenges are available every day.', 'Your streak increases when you complete daily challenges consistently.', 'Missing a day will reset your current streak.']],
            ['3. Content', ['Uploaded content must be your own work.', 'Your content is used only for AI scoring and is private.', 'Uploading illegal or inappropriate content is prohibited.']],
            ['4. Interaction', ['Users can follow and poke others.', 'Chat features are not available.', 'Spamming or harassment is not allowed.']],
            ['5. Leaderboard & Statistics', ['Rankings are based on user activity and streak consistency.', 'Statistics are shown in summary form.']],
            ['6. AI Features', ['Challenges are generated by Gemini AI.', 'AI scoring is automated and may not always be accurate.', 'AI decisions are not final and are for guidance only.']],
            ['7. Changes', ['OnePercent may update features and terms at any time.', 'Continued use of the app constitutes acceptance of new terms.']],
        ] as [$title, $points])
                <div>
                    <h3 class="font-bold text-gray-800 mb-3">{{ $title }}</h3>
                    <ul class="space-y-2">
                        @foreach ($points as $point)
                            <li class="flex items-start gap-2 text-sm text-gray-600">
                                <span class="text-primary mt-0.5">•</span>
                                {{ $point }}
                            </li>
                        @endforeach
                    </ul>
                </div>
            @endforeach

            <div class="pt-4 border-t border-gray-100 text-center text-sm text-gray-400">
                Last updated: May 2026
            </div>
        </div>
    </div>
@endsection
